version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: wicm-api-db
    restart: unless-stopped
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}